### ISSUE TITLE
Only HK1 and HK2 are shown, HK3 not available 

### ISSUE THREAD

**Issue by starlight2k** [pail23/stiebel_eltron_isg_component#197]
Hello,

i have 3 heat circuits, but only temps for 1 and 2 are shown, 3 is not available. 

Is there any chance to get HK3 ?
With the extension WPE its even possible to have more heat circuits

https://github.com/pail23/stiebel_eltron_isg_component/issues/89#issuecomment-1756155468
only shows values for HK3 from FET, but not from heat pump. 

![Screenshot 2024-02-12 095316](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/9d6b2d46-37ef-4108-9006-3348e10c0ecd)

**Comment by Padanian** [comment]
I'll pick this one up in the next few days

**Comment by starlight2k** [comment]
maybe also interesting.. 

if you have another pt1000 for cooling, its now register 523

![Screenshot 2024-02-13 002744](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/8900279b-d875-434b-a91a-66bc7c264330)
![Screenshot 2024-02-13 002728](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/c5395792-b387-4d04-b619-7bff6bdd8ca0)

**Comment by Padanian** [comment]
I have contacted the headquarter in Germany and asked confirmation.
I'm not confident to implement registers based on a deduction or reverse engineering.

**Comment by starlight2k** [comment]
you are right, WPM4 is WPMsystem. 
so it must be related to the software version of the ISG

![Screenshot 2024-02-13 091750](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/40b9e170-abc0-4ca1-adb7-c851049f0eb4)

**Comment by Padanian** [comment]
Anyway, it is apparent the ISG manual is incomplete. Waiting for a feedback from headquarters.

**Comment by Padanian** [comment]
> if you have another pt1000 for cooling, its now register 523

It's 524, actually.
I have implemented 524 to 527 and HK3 water temperatures. 
To be tested by anyone with such parameters populated.

**Comment by starlight2k** [comment]
There must be something wrong in code

it read out target temp, but actual temp is disabled...
after activate manual , 
whole plugin fails. 

`

Logger: homeassistant.loader
Source: loader.py:842
First occurred: 20:36:28 (1 occurrences)
Last logged: 20:36:28
Unexpected exception importing platform custom_components.stiebel_eltron_isg.climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/stiebel_eltron_isg/climate.py", line 148, in <module>
    class StiebelEltronISGClimateEntity(StiebelEltronISGEntity, ClimateEntity):
  File "/config/custom_components/stiebel_eltron_isg/climate.py", line 156, in StiebelEltronISGClimateEntity
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF

`


` Logger: homeassistant.setup
Source: setup.py:403
First occurred: 20:36:28 (1 occurrences)
Last logged: 20:36:28
Unable to prepare setup for platform 'stiebel_eltron_isg.climate': Platform not found (Exception importing custom_components.stiebel_eltron_isg.climate)`

**Comment by Padanian** [comment]
Did you update to 2024.2?

**Comment by starlight2k** [comment]
now updated, not breaking anymore but still not showing values

![Screenshot 2024-02-13 205905](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/c152b2a4-ca02-41c1-a86f-2afd2c64cab3)
![Screenshot 2024-02-13 205839](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/5b91372e-7379-4190-b01e-31234f9b2422)
![Screenshot 2024-02-13 205830](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/0e8aa5de-eaaa-4616-8683-3b224405af02)

**Comment by starlight2k** [comment]
aha, looks like you swapped the modbus address

![Screenshot 2024-02-13 210358](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/ec6529bd-25f9-4034-9e1e-095b3e8b9edd)

**Comment by starlight2k** [comment]
- name: HK3_ist
      unit_of_measurement: °C
      device_class: temperature
      address: 609
      scale: 0.1
      slave: 1
      input_type: input
      data_type: int16
    - name: HK3_soll
      unit_of_measurement: °C
      device_class: temperature
      address: 610
      scale: 0.1
      slave: 1
      input_type: input
      data_type: int16
    - name: cooling_actual
      unit_of_measurement: °C
      device_class: temperature
      address: 523
      scale: 0.1
      slave: 1
      input_type: input
      data_type: int16


![Screenshot 2024-02-13 210852](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/cabc970e-f260-49cf-a868-61d8ec1ed017)
![Screenshot 2024-02-13 210820](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/0fb1fe6c-2b12-43a1-92c3-2992c3315630)

**Comment by Padanian** [comment]
> aha, looks like you swapped the modbus address

It's not that I swapped the addresses. It's just that they are undocumented. 
Provided HK1 and HK2 ordering is actual first, target second, I assumed it was the same.
Can you please double check this is the case.

**Comment by starlight2k** [comment]
i dont get it,

i checked the code , 609 and 610 should be correct. i deleted custom components, parsed it manually from main, rebooted 100 times, but it still reading actual as target. 

any idea if its a problem with my HA or code?

![Screenshot 2024-02-14 110450](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/a17380ed-f905-4337-ac5e-7b4c1a096121)
![Screenshot 2024-02-14 110441](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/fffeec89-a458-46e4-8bf4-0a3049c594ef)
![Screenshot 2024-02-14 111340](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/21c9e6ad-b75c-45ee-84bb-7cd7bb3a8960)

**Comment by starlight2k** [comment]
`            # 604-609 COOLING CIRCUIT TEMPERATURE_HK1 to HK5
            decoder.skip_bytes(28)
            # 610
            result[ACTUAL_TEMPERATURE_HK3] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )
            # 611
            result[TARGET_TEMPERATURE_HK3] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )`

wpm_coordinator.py

this will fix it, i dont understand why. 
the plugin reads everything +1?

![Screenshot 2024-02-14 112319](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/7b7530bf-283a-43f3-a314-c513b5f71fc9)
![Screenshot 2024-02-14 112307](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/549246db-5505-4a9d-8a91-036b1ba00bfe)

**Comment by Padanian** [comment]
> ```
>         # 604-609 COOLING CIRCUIT TEMPERATURE_HK1 to HK5
>         decoder.skip_bytes(28)
>         # 610
>         result[ACTUAL_TEMPERATURE_HK3] = get_isg_scaled_value(
>             decoder.decode_16bit_int()
>         )
>         # 611
>         result[TARGET_TEMPERATURE_HK3] = get_isg_scaled_value(
>             decoder.decode_16bit_int()
>         )
> ```
> 
> wpm_coordinator.py
> 
> this will fix it, i dont understand why. the plugin reads everything +1?

@pail23 can you confirm the base address of the function is +1?

**Comment by starlight2k** [comment]
for some reason, the plugin reads everything +1 (starting from 1)
and the modbus plugin from homeassistant ready everything starting from 0

so if i read them with the modbus plugin ,,, its 523 (cooling) / 609 (actual HK3) / 610 (target hK3)
but plugin its 524/610/611

so my mistake :(



![Screenshot 2024-02-14 113529](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/b397399f-a0bb-4507-bdc8-784ddaf3c688)
![Screenshot 2024-02-14 113542](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/a9c245fc-854e-414f-a472-69afc9648048)
![Screenshot 2024-02-14 113450](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/9dc3e638-e80c-41ea-8c16-2553ea1648df)
![Screenshot 2024-02-14 113507](https://github.com/pail23/stiebel_eltron_isg_component/assets/93672472/b16bcaa5-6eec-40fd-a383-8d95fd70cd06)

**Comment by Padanian** [comment]
@pail23 How would you like to proceed for fixing it?

**Comment by starlight2k** [comment]
> Sorry, but why are you uploading a picture of cooling fancoil? It is confusing.

Maybe its confusing. 

There are two possibilities to use the heat pump for cooling:

**Comment by Padanian** [comment]
> Maybe its confusing.

Yes, thanks, I am actually from Stiebel Eltron, so I am familiar with how it works.
Confusing was the picture of HK3 target temperature together with fancoil cooling. I didn't see the relationship.

**Comment by mapo-89** [comment]
is it possible to integrate also the climate entity or target temperature input_number entity for HC3?

**Comment by Padanian** [comment]
It's already implemented, registers 592 to 595. 
@pail23 these registers 609 and 610 are undocumented and overlap 592 and 593 in wpm_coordinator

```
            # 609
            result[ACTUAL_TEMPERATURE_HK3] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )
            # 610
            result[TARGET_TEMPERATURE_HK3] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )
```

**Comment by starlight2k** [comment]
@mapo-89 

do you have HK3?
can you report back if actual and target temp shows correctly ?
still no idea if 609/610 or 610/611


@Padanian 
its stiebel eltron, a german company. they are slow with everything and it will take decades before they will release a new doc

while you fill unease with it i added it like this


            # 531 External Heater
            result[ACTUAL_TEMPERATURE_EXT] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )
            # 532 External Heater 
            result[TARGET_TEMPERATURE_EXT] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )


            # 610
            result[ACTUAL_TEMPERATURE_HK3] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )
            # 611
            result[TARGET_TEMPERATURE_HK3] = get_isg_scaled_value(
                decoder.decode_16bit_int()
            )


for me its working. also the external heater which is not available in main fork

**Comment by mapo-89** [comment]
@starlight2k 
I do not receive any data from the sensor for the actual temperature HC3, but the target temperature receives the actual temperature

**Comment by starlight2k** [comment]
Thanks for verification. 

need to be changed to 610/611 
not 609/610.

**Comment by mapo-89** [comment]
short question: Why am I not able to see the climate sensor for HC3?
![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/118180259/983d5374-a7d7-4c76-bd37-c8c4bfab8fd7)

**Comment by Padanian** [comment]
> while you fill unease with it i added it like this

I'm happy it works for you, but hey, I'm volunteering as you are. Feel free to commit your code.
There are not many units with 3 circuits out there, and I can't reverse engineer all registers.
Also it is unexplicable why all other sequence of registers are in line, and registers from 501 onwards are shifted by 1.

**Comment by LaurinD** [comment]
i made a pull for HC 3 and climate 3 now. it works on my system

**Comment by NorbertBauer** [comment]
i am also missing the heating curve für HK3

**Comment by LaurinD** [comment]
In the version i coded in Dec. it works. maybe ja have an old version or you have to activate the entity.
![HK3](https://github.com/user-attachments/assets/b55f763e-fb56-42d1-95f8-765a1acfd24d)
![hk3 activate](https://github.com/user-attachments/assets/3deebeac-f373-47a0-af76-3745aff8d7c7)

**Comment by NorbertBauer** [comment]
i am using the version that i have installed via HACS.

![image](https://github.com/user-attachments/assets/71fec8f3-a847-46be-a298-5a2ec084726a)

**Comment by piporulez** [comment]
i  also have some trouble with the integration and HK3. 

i changed the IDs for the Actual Temperature / Current Temperature (like metioned here - https://github.com/pail23/stiebel_eltron_isg_component/issues/197#issuecomment-2046074354), but the target temperature is still showing the actual temperature. The stiebel_eltron_isg_actual_temperature_hk_3 is still not available, altough the entity is active.
I also not have the heating curve for HK3.

What i am missing here? I am using this version from HACS
![image](https://github.com/user-attachments/assets/b219c20a-9ea6-402a-aaa4-e9013aa8e886)

Thanks in advance for your replies!

**Comment by LaurinD** [comment]
Oh i am sorry.
I am not a good coder and quite new on Github. Maybe my version was not included in the actual release.
I hope you can add my repository.
![HK3Repository](https://github.com/user-attachments/assets/dcba885e-f646-4f84-b035-48e6abc0cef5)
insert this:
https://github.com/LaurinD/stiebel_eltron_isg_component.git
![repo](https://github.com/user-attachments/assets/32ae65cc-8aa4-4634-ac85-d5ab2c9077f5)
But i am not sure if this is the way to do this. Let me now if it works

**Comment by piporulez** [comment]
@LaurinD . can you explain a bit what you changed exactly? Maybe i can change it manually in my current installed version?

I am a bit confusing about this hint, so i don't want to have other issues after installing another Version of the ISG Extensions

![Image](https://github.com/user-attachments/assets/5deeedc3-1a23-412a-9263-be9747b9be19)

Thanks in advance!

**Comment by LaurinD** [comment]
Hmm i don´t know i think its better to wait for a new release of the repo. If you change the code by hand you can cause some troubele.
